### ISSUE TITLE
add possibility to use transparent node animation for dragging

### ISSUE THREAD

**Issue by DaHaiz** [ONE-LOGIC/ngFlowchart#23]
Currently there can be a huge performance issue while dragging if you have a lot of watchers in your angular app. This is because the scope is used to handle the position of the nodes as well as the edges connected to it.

To reduce digest cycles add another mode for dragging where only a transparent copy of the node is used to display the new position using vanilla js and only update the scope at the end of dragging.

**Comment by maurerke** [comment]
Done with commit 6580b6be8e8e357e52c6d9cb2570ccfd1530302a

Use `drag-animation="'shadow'"` to get performance improvement
